//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatioDeAutomoveis
{
    using System;
    using System.Collections.Generic;
    
    public partial class alocacao
    {
        public byte id { get; set; }
        public byte area { get; set; }
        public byte automovel { get; set; }
        public byte concession_ria { get; set; }
        public byte quantidade { get; set; }
    }
}
