//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatioDeAutomoveis
{
    using System;
    using System.Collections.Generic;
    
    public partial class automoveis
    {
        public byte id { get; set; }
        public string modelo { get; set; }
        public decimal pre_o { get; set; }
    }
}
